server:
  port: 8087

spring:  application:    name: API-GATEWAY
  cloud:    gateway:      routes:      - id: GUARDIAN-APP
        uri: lb://GUARDIAN-APP
        predicates:
          - Path=/api/news/guardian
      - id: NYT-APP
        uri: lb://NYT-APP
        predicates:
          - Path=/api/news/nyt
      - id: NEWS-APP
        uri: lb://NEWS-APP
        predicates:
          - Path=/api/newsApp

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka